module Aws
  module Sigv4
    module Errors
      class MissingCredentialsError < ArgumentError
        def initialize: (?String msg) -> void
      end

      class MissingRegionError < ArgumentError
        def initialize: (*untyped) -> void
      end
    end
  end
end